# Generated by Django 5.0 on 2023-12-11 11:19

import django.core.validators
import fruitipedia.core.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='fruit_name',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2), fruitipedia.core.custom_validators.validate_all_letters], verbose_name='Name'),
        ),
    ]
